/*
 * usart_config.c
 *
 * Created: 2023-05-25 4:36:45 PM
 *  Author: khale
 */ 
#include "usart_config.h"

st_USART_CONFIG_t g_st_USART_config_channel_1 = {
	.en_USART_BAUD_RATE = USART_9600,
	.en_USART_OPERATION_MODE = USART_ASYNC,
	.en_USART_OPERATION_ROLE = USART_DUAL_ROLE,
	.en_USART_TRANSMISSION_SPEED = USART_NORMAL_SPEED,
	.en_USART_DATA_FRAME_SIZE = USART_DATA_8_BITS,
	.en_USART_PARITY_BIT = USART_PARITY_DISABLED,
	.en_USART_STOP_BIT = USART_STOP_1_BIT,
	.en_USART_INTERRUPT_MODE = USART_INTERRUPT_MODE
};